export const doctorsData = [
  {
    id: 1,
    name: "Dr. Sarah Johnson",
    specialization: "Cardiology",
    experience: 15,
    status: "available",
    rating: 4.8,
    consultations: 1250,
    nextAvailable: "10:00 AM",
    avatar: null,
  },
  {
    id: 2,
    name: "Dr. Michael Chen",
    specialization: "Dermatology",
    experience: 12,
    status: "busy",
    rating: 4.9,
    consultations: 980,
    nextAvailable: "2:00 PM",
    avatar: null,
  },
  {
    id: 3,
    name: "Dr. Emily Williams",
    specialization: "Pediatrics",
    experience: 10,
    status: "available",
    rating: 4.7,
    consultations: 1100,
    nextAvailable: "11:30 AM",
    avatar: null,
  },
  {
    id: 4,
    name: "Dr. James Brown",
    specialization: "Orthopedics",
    experience: 18,
    status: "available",
    rating: 4.9,
    consultations: 1450,
    nextAvailable: "9:00 AM",
    avatar: null,
  },
  {
    id: 5,
    name: "Dr. Lisa Anderson",
    specialization: "Neurology",
    experience: 14,
    status: "offline",
    rating: 4.6,
    consultations: 890,
    nextAvailable: "Tomorrow",
    avatar: null,
  },
  {
    id: 6,
    name: "Dr. Robert Taylor",
    specialization: "General Medicine",
    experience: 8,
    status: "available",
    rating: 4.5,
    consultations: 750,
    nextAvailable: "1:00 PM",
    avatar: null,
  },
  {
    id: 7,
    name: "Dr. Maria Garcia",
    specialization: "Psychiatry",
    experience: 11,
    status: "busy",
    rating: 4.8,
    consultations: 920,
    nextAvailable: "4:00 PM",
    avatar: null,
  },
  {
    id: 8,
    name: "Dr. David Miller",
    specialization: "Ophthalmology",
    experience: 16,
    status: "available",
    rating: 4.7,
    consultations: 1050,
    nextAvailable: "10:30 AM",
    avatar: null,
  },
];

export const appointmentsData = [
  {
    id: 1,
    patient: "John Smith",
    doctor: "Dr. Sarah Johnson",
    date: "2025-11-28",
    time: "10:00 AM",
    status: "scheduled",
    type: "Video",
  },
  {
    id: 2,
    patient: "Emma Wilson",
    doctor: "Dr. Michael Chen",
    date: "2025-11-28",
    time: "2:00 PM",
    status: "completed",
    type: "Video",
  },
  {
    id: 3,
    patient: "Oliver Brown",
    doctor: "Dr. Emily Williams",
    date: "2025-11-29",
    time: "11:30 AM",
    status: "scheduled",
    type: "Video",
  },
  {
    id: 4,
    patient: "Sophia Davis",
    doctor: "Dr. James Brown",
    date: "2025-11-27",
    time: "9:00 AM",
    status: "cancelled",
    type: "Video",
  },
  {
    id: 5,
    patient: "Liam Johnson",
    doctor: "Dr. Lisa Anderson",
    date: "2025-11-30",
    time: "3:00 PM",
    status: "scheduled",
    type: "Video",
  },
  {
    id: 6,
    patient: "Ava Martinez",
    doctor: "Dr. Robert Taylor",
    date: "2025-11-26",
    time: "11:00 AM",
    status: "completed",
    type: "Video",
  },
];

export const patientsData = [
  {
    id: 1,
    name: "John Smith",
    email: "john.smith@email.com",
    phone: "+1 234-567-8901",
    lastVisit: "2025-11-20",
    status: "active",
  },
  {
    id: 2,
    name: "Emma Wilson",
    email: "emma.w@email.com",
    phone: "+1 234-567-8902",
    lastVisit: "2025-11-25",
    status: "active",
  },
  {
    id: 3,
    name: "Oliver Brown",
    email: "oliver.b@email.com",
    phone: "+1 234-567-8903",
    lastVisit: "2025-10-15",
    status: "inactive",
  },
  {
    id: 4,
    name: "Sophia Davis",
    email: "sophia.d@email.com",
    phone: "+1 234-567-8904",
    lastVisit: "2025-11-18",
    status: "active",
  },
  {
    id: 5,
    name: "Liam Johnson",
    email: "liam.j@email.com",
    phone: "+1 234-567-8905",
    lastVisit: "2025-11-22",
    status: "active",
  },
  {
    id: 6,
    name: "Ava Martinez",
    email: "ava.m@email.com",
    phone: "+1 234-567-8906",
    lastVisit: "2025-11-10",
    status: "inactive",
  },
];
